---
title: "Unix toolkit"
author: "Dr. Alexander Fisher"
execute:
  warning: true
format: 
    revealjs:
      smaller: true
---

# basic tools

## simple cheat sheet

A "folder" aka a "directory" is a container. A "file\* is an element of a container, e.g. `lab-1.qmd` is a file contained in a `lab-1-username` directory.

+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| command                          | action                                                                                                                         |
+==================================+================================================================================================================================+
| `$ ls`                           | list files in current directory                                                                                                |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `$ pwd`                          | print working directory                                                                                                        |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `$ cd`                           | change directory\                                                                                                              |
|                                  | example: `$ cd ..` to go to parent directory                                                                                   |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `$ mkdir dname`                  | make directory "dname"                                                                                                         |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `$ mkdir s{1..5}`                | overpowered file creation                                                                                                      |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `$ rm /path/to/file`             | remove a file                                                                                                                  |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `$ rm -rf dname`                 | recursively remove a directory and its contents                                                                                |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `$ rm core*`                     | remove all objects in the current working directory that begin with "core"                                                     |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `$ wc -l`                        | show \# lines in a file                                                                                                        |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `$ y > x.txt`                    | pass printed output from command "y" on the left to file "x.txt" on the right\                                                 |
|                                  | example: `$ head -N file1.txt > file2.txt` creates a new file called "file2" that is a replica of the first N lines of file 1\ |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `$ echo 'text here' >> filename` | add text to the end of a file                                                                                                  |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `$ man x`                        | pull up documentation for command x, example: `$ man ls`                                                                       |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+

## paths

## pathfinding

### absolute paths

### relative paths

## Exercise

# Miscellaneous tools

## word count

## pdfcrop

## combine pdfs or pngs

## awk

## Exercise
